"""Project and workflow templates.

Templates are plain YAML files under ``templates/<stack>/`` containing
``{{ placeholder }}`` markers. A placeholder that forms a whole YAML value is
rendered as a JSON-quoted scalar (always valid YAML); one embedded in other text
is inserted verbatim. Lines whose whole-value placeholders resolve to nothing
are dropped, and workflow steps left without a command are pruned.
"""

from __future__ import annotations

import json
import re
from collections.abc import Iterable, Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

import highhx

PLACEHOLDER_RE = re.compile(r"\{\{\s*([A-Za-z_][\w.]*)\s*\}\}")
WHOLE_VALUE_RE = re.compile(r"^(\s*(?:-\s+|[\w.\-\"']+:\s+))\{\{\s*([A-Za-z_][\w.]*)\s*\}\}\s*$")
HEADER = "# Generated by HighhX from a template. Edit freely.\n"


def templates_root() -> Path | None:
    """Location of the bundled templates (installed package or source checkout)."""
    package_dir = Path(highhx.__file__).resolve().parent
    for candidate in (package_dir / "_templates", package_dir.parent.parent / "templates"):
        if (candidate / "generic").is_dir():
            return candidate
    return None


def lookup(context: Mapping[str, Any], dotted: str) -> Any:
    current: Any = context
    for part in dotted.split("."):
        if isinstance(current, Mapping) and part in current:
            current = current[part]
        else:
            return None
    return current


def _empty(value: Any) -> bool:
    return value is None or value in ("", [], {})


def render(text: str, context: Mapping[str, Any]) -> str:
    """Render placeholders; comment lines are left untouched."""
    lines: list[str] = []
    for line in text.splitlines():
        if line.lstrip().startswith("#"):
            lines.append(line)
            continue
        whole = WHOLE_VALUE_RE.match(line)
        if whole:
            value = lookup(context, whole.group(2))
            if _empty(value):
                continue
            lines.append(f"{whole.group(1)}{json.dumps(value)}")
            continue
        lines.append(PLACEHOLDER_RE.sub(lambda m: "" if _empty(v := lookup(context, m.group(1))) else str(v), line))
    return "\n".join(lines) + "\n"


def prune_workflow(text: str) -> str | None:
    """Drop steps without ``run``/``uses`` and dangling ``depends_on`` references.

    Returns None when no steps remain. Text is returned unchanged if nothing was pruned.
    """
    data = yaml.safe_load(text)
    if not isinstance(data, dict):
        return None
    steps = data.get("steps") or []
    kept = [s for s in steps if isinstance(s, dict) and (s.get("run") or s.get("uses"))]
    if len(kept) == len(steps):
        return text if kept else None
    if not kept:
        return None
    ids = {s.get("id") for s in kept}
    removed = {s.get("id") for s in steps if isinstance(s, dict)} - ids
    for step in kept:
        deps = step.get("depends_on")
        if isinstance(deps, str):
            deps = [deps]
        if deps:
            # Re-wire dependencies through removed steps to their own dependencies.
            resolved: list[str] = []
            queue = list(deps)
            by_id = {s.get("id"): s for s in steps if isinstance(s, dict)}
            while queue:
                dep = queue.pop(0)
                if dep in ids and dep not in resolved:
                    resolved.append(dep)
                elif dep in removed:
                    inner = by_id[dep].get("depends_on") or []
                    queue.extend([inner] if isinstance(inner, str) else inner)
            if resolved:
                step["depends_on"] = resolved
            else:
                step.pop("depends_on", None)
    data["steps"] = kept
    return HEADER + yaml.safe_dump(data, sort_keys=False, default_flow_style=False, width=1000)


@dataclass
class RenderedProject:
    """Files produced for ``highhx init`` (paths relative to ``.highhx/``)."""

    files: dict[str, str]
    stack: str


class TemplateLibrary:
    """Bundled templates plus extra template directories (e.g. from plugins)."""

    def __init__(self, extra_dirs: Iterable[Path] = ()) -> None:
        self.root = templates_root()
        self.extra_dirs = [Path(d) for d in extra_dirs]

    def stacks(self) -> list[str]:
        names: set[str] = set()
        for base in self._bases():
            names.update(p.name for p in base.iterdir() if p.is_dir())
        return sorted(names)

    def _bases(self) -> list[Path]:
        bases = [d for d in self.extra_dirs if d.is_dir()]
        if self.root is not None:
            bases.append(self.root)
        return bases

    def _find(self, stack: str, relative: str) -> Path | None:
        for base in self._bases():
            for candidate in (base / stack / relative, base / "generic" / relative):
                if candidate.is_file():
                    return candidate
        return None

    def workflow_templates(self, stack: str = "generic") -> dict[str, Path]:
        """Workflow template files available for ``stack`` (stack overrides generic)."""
        found: dict[str, Path] = {}
        for base in reversed(self._bases()):
            for directory in (base / "generic" / "workflows", base / stack / "workflows"):
                if directory.is_dir():
                    for path in sorted(directory.glob("*.yaml")):
                        found[path.stem] = path
        return dict(sorted(found.items()))

    def render_workflow(self, template: str, context: Mapping[str, Any], stack: str = "generic") -> str | None:
        path = self.workflow_templates(stack).get(template)
        if path is None:
            return None
        return prune_workflow(render(path.read_text(encoding="utf-8"), context))

    def render_project(
        self, stack: str, context: Mapping[str, Any], *, workflows: Iterable[str] | None = None
    ) -> RenderedProject:
        files: dict[str, str] = {}
        for name in ("config.yaml", "environment.yaml", "policies.yaml"):
            path = self._find(stack, name)
            if path is not None:
                files[name] = render(path.read_text(encoding="utf-8"), context)
        wanted = set(workflows) if workflows is not None else None
        for name, path in self.workflow_templates(stack).items():
            if wanted is not None and name not in wanted:
                continue
            rendered = prune_workflow(render(path.read_text(encoding="utf-8"), context))
            if rendered is not None:
                files[f"workflows/{name}.yaml"] = rendered
        return RenderedProject(files=files, stack=stack)


BLANK_WORKFLOW = """name: {name}
description: {description}
settings:
  fail_fast: true
  max_parallel: 4
steps:
  - id: hello
    name: Say hello
    run: {command}
"""
